package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/edufriendchen/hertz-vue-admin/server Begin; DO NOT EDIT.

	// Code generated by github.com/edufriendchen/hertz-vue-admin/server End; DO NOT EDIT.
}

